### ISSUE TITLE
[PE-D][Tester D] Save File is not readable in windows

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-4/tp#106] opened 2023-04-01 01:39 UTC
The save file is also not human readable on windows. This has resulted in this and the previous issue on being non-readable on linux become a high severity bug. See [constraints](https://nus-cs2113-ay2223s2.github.io/website/admin/tp-constraints.html#constraint-human-editable-file)

Expected: Human readable - and therefore human editable save file

Actual: Non readable file with occational snippets of readable segments (see screenshot below)

![image.png](https://raw.githubusercontent.com/matthew-liu-zhenjie/ped/main/files/977e1fb0-ea23-406b-bc70-d8340991b2d8.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: matthew-liu-zhenjie/ped#4

**Comment by ERJUNZE** [comment] 2023-04-01 10:32
Duplicate of #80

**Closed by ERJUNZE** 2023-04-01 10:32 UTC
Labels: type.Bug, Duplicate
